### ISSUE TITLE
error when launch cheetah

### ISSUE THREAD

**Issue by Donneur2lumiere** [ShorelineCrypto/cheetah_cpuminer#5]
Run under ubuntu 20.04 with ryzen 5800x, Ram 16Go, rog b550-e
I have install the library with : 
```
sudo pip3 install python-bitcoinrpc
Requirement already satisfied: python-bitcoinrpc in /usr/local/lib/python3.8/dist-packages (1.0)

```
error log :
`Traceback (most recent call last):
  File "main.py", line 30, in <module>
    import cpuminer.cheetah as cheetah
  File "/media/DataWin/marechal/Downloads/Lin/Logiciel-PROV/neng/cheetah_cpuminer/cpuminer/cheetah.py", line 3, in <module>
    from bitcoinrpc.authproxy import AuthServiceProxy, JSONRPCException
ImportError: No module named bitcoinrpc.authproxy
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    import cpuminer.cheetah as cheetah
  File "/media/DataWin/marechal/Downloads/Lin/Logiciel-PROV/neng/cheetah_cpuminer/cpuminer/cheetah.py", line 3, in <module>
    from bitcoinrpc.authproxy import AuthServiceProxy, JSONRPCException
ImportError: No module named bitcoinrpc.authproxy
`
What do master ?

**Comment by ShorelineCrypto** [comment]
The bitcoinrpc.authproxy  module was not installed properly in Ubuntu 20.04. 

Please note in Ubuntu 20.04,  the default python is python3,  not python2.  The code require python2.7.   Try below:

`sudo pip2 install python-bitcoinrpc`

**Comment by Donneur2lumiere** [comment]
ok, i have to install pip2 with the help of this page :
https://www.gungorbudak.com/blog/2018/08/02/correct-installation-and-configuration-of-pip2-and-pip3/

i was abble to launch cheettah.
you can close this case great master
