### ISSUE TITLE
what is the difference between cheetahcoin and nengcoin? can I use this to mine cheetahcoin?

### ISSUE THREAD

**Issue by idoor88** [ShorelineCrypto/cheetah_cpuminer#6]
I am a newbie of mining, what is the difference between cheetahcoin and nengcoin? can I use this to mine cheetahcoin?

**Comment by ShorelineCrypto** [comment]
Nengcoin was the original coin that invented this new way of CPU mining,  also this software "Cheetah_Cpuminer"  software started with Nengcoin 3 years ago. 

Cheetahcoin is another coin project, a meme coin that cloned the same CPU mining tech from Nengcoin.  Cheetahcoin is on "chta"  branch of this miner.  You should start to learn one coin only, stick with Cheetahcoin first, and make sure you learn how to do CPU mining in your android phone.   The profit of CPU mining is more on phone than PC.
